name: models_weebi
version: 1.0.16
#publish_to: #https://onepub.dev/api/xnxpsdavuh/
homepage: http://weebi.com
description: models
environment: 
  sdk: '>=2.19.6 <4.0.0' 
dependencies: 
  collection: ^1.14.12
  http: ^0.13.4
  meta: ^1.3.0 # ^1.7.0
  mobx: ^2.0.3
  ### weebi's own kitchen
  models_base: ^1.4.4
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4
