name: models_weebi
description: A starting point for Dart libraries or applications.
version: 1.0.5
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  mobx: ^2.0.3 #^1.2.1+4 #
  intl: ^0.17.0
  models_base: ^1.2.7

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4 #^1.11.5
  mobx_codegen: ^2.0.4 #^2.0.1+3 #mobx_codegen: ^1.1.2
  #pedantic: ^1.10.0 #^1.9.2 #
