import 'package:models_weebi/common.dart';
import 'package:models_weebi/src/models/article.dart';
import 'package:models_weebi/src/models/articles_lines.dart';
import 'package:models_weebi/utils.dart';

class JamfBM {
  static final jams = [
    ArticleLines(
      id: 1,
      title: 'Confiture BM Peches',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 1,
          id: 1,
          fullName: 'Confiture BM Peches 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1uXHH8H6cxdkkRvBaUjx1lm8NNMcRzZ5c',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 11,
          codeEAN: '3 04532000154 9',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 2,
      title: 'Confiture BM Compotee Abricot',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 2,
          id: 1,
          fullName: 'Confiture BM Compotee Abricot 600g',
          photo:
              'https://drive.google.com/uc?export=view&id=1tDVvQd2PY6HY0pPrmLlKD_XYDXnUkRp5',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 21,
          codeEAN: '3 04532000690 2',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 3,
      title: 'Confiture BM Figues violettes',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 3,
          id: 1,
          fullName: 'Confiture BM Figues violettes 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1iXr7_ObaHiak2yTjPoPCvDK4gANNgbg4',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 31,
          codeEAN: '3 04532000929 3',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 4,
      title: 'Confiture BM Oranges ameres',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 4,
          id: 1,
          fullName: 'Confiture BM Oranges ameres 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1hiTwDl3tGVFXmbtnQr-E1_ijlHhELgCn',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 41,
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 5,
      title: 'Confiture BM Abricots',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 5,
          id: 1,
          fullName: 'Confiture BM Abricots 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1ekgvdZBj-b32EKH1V4aA1zwlpT6XSr0C',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          codeEAN: '3 04532000153 2',
          articleCode: 51,
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 6,
      title: 'Confiture BM Fraises',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 6,
          id: 1,
          fullName: 'Confiture BM Fraises 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1ao2NMd5zQUnQItGJRXIL3Z9qDEn7JAF3',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 61,
          codeEAN: '3 04532000152 5',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 7,
      title: 'Confiture BM Framboises',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 7,
          id: 1,
          fullName: 'Confiture BM Framboises 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1alCaEDEHcpmi5CD1s0mwirEh1eoA1bYU',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          codeEAN: '3 04532000157 0',
          articleCode: 71,
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 8,
      title: 'Confiture BM Cerises noires',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 8,
          id: 1,
          fullName: 'Confiture BM Cerises noires 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1XiKinQC_apuKZVQTm5NGtmspD9I2oPhm',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 81,
          codeEAN: '3 04532002327 5',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 9,
      title: 'Confiture BM Gelee de mures',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 9,
          id: 1,
          fullName: 'Confiture BM Gelee de mures 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1To1lgzRuugaP24hh9uUmG5gGG0IACflp',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 91,
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 10,
      title: 'Confiture BM Fruits des Bois',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 10,
          id: 1,
          fullName: 'Confiture BM Fruits des Bois 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=1Q_Ra304rrk82ULx-x0X5S9nUrRBKX9pa',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 101,
          codeEAN: '3 04532000719 0',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 11,
      title: 'Confiture BM Cerises griottes',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 11,
          codeEAN: '3 04532000151 8',
          id: 1,
          fullName: 'Confiture BM Cerises griottes 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=19TyumiFVM8RvxRfcCVkAhJwR8Dm8etfY',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 111,
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 12,
      title: 'Confiture BM Compotee Peches',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 12,
          id: 1,
          fullName: 'Confiture BM Compotee Peches 600g',
          photo:
              'https://drive.google.com/uc?export=view&id=17ITVvQF36CryTLyTDOPLjnmNfHZrefYl',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 121,
          codeEAN: '3 04532000691 9',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 13,
      title: 'Confiture BM Quetsches',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 13,
          id: 1,
          fullName: 'Confiture BM Quetsches 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=15GBuBpR6x_4PVA-CAXgOzkzsbfCxWgEa',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 131,
          codeEAN: '3 04532000160 0',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
    ArticleLines(
      id: 14,
      title: 'Confiture BM 4 Fruits',
      stockUnit: StockUnit.unit,
      status: true,
      statusUpdateDate: WeebiDates.defaultDate,
      creationDate: WeebiDates.defaultDate,
      updateDate: WeebiDates.defaultDate,
      articles: [
        Article(
          lineId: 14,
          id: 1,
          fullName: 'Confiture BM 4 Fruits 370g',
          photo:
              'https://drive.google.com/uc?export=view&id=11ZtZjRcgjuRKHK-mq2VL1geUYl1rb5-i',
          photoSource: PhotoSource.network,
          weight: 1.0,
          price: 100,
          cost: 50,
          articleCode: 141,
          codeEAN: '3 04532000165 5',
          creationDate: WeebiDates.defaultDate,
          updateDate: WeebiDates.defaultDate,
        ),
      ],
    ),
  ];
}
